# Header
menu:
  Home: /
  Linux: /linux
  PHP: /php
  Python: /python
  GO: /go
  Flash: /flash
  Git: /git
  漏洞: /bug
  缓存: /cache
  代理: /proxy
  其他: /other

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
